### ISSUE TITLE
Add "Generate" class of workflows + upgrade Workspace UI

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#356]
### Details
We are adding a new workflow to the CK Workflows modal that is a generative task workflow that students will complete in groups from the CK Workspace.
![Screenshot 2023-03-24 at 11 57 23 AM](https://user-images.githubusercontent.com/6416247/227577613-3dbd45b4-fbc5-461e-acbc-a79810366364.png)

**Details**
This will involve a new workflow option and new input fields under the Create Workflow tab as well as updates to the Manage tab to enable the new workflow type. Finally, students will complete the generation tasks from the CK Workspace.

**Tasks**
***Create Workflows***

- [ ] In the Workflow editor we should now have three options (i) Distribution Workflow, (ii) [NEW] Generation Task Workflow, (iii) [Rename "Task Workflow" to] Peer Review Workflow

- [ ] The input fields for Generation Task Workflow should include (i) Workflow Name [must enter text], (ii) Num of Posts to Generate [this could be a slider limited to the range of 1 to 10 posts with a default value of 1], (iii) Destination [must select a canvas or any bucket], Assigned Groups [must select one or more groups], Prompt: [must enter a text prompt]

An example of the input fields could be:
Workflow name: Generate math problems
Num of posts to generate: 5
Destination: Math Problem Board
Assigned Groups: Group1, Group2
Prompt: “Please create 5 math problems and tag each problem with the content domain it addresses”

***Workflow requirements:***

- [ ] [If time permits, we can also add support for additional workflow requirements such as] Add the header "Workflow Requirements" (as we have for the Peer Review Workflow) and provide a checkbox option for "Require minimum of 1 tag"

e.g.,
o Require minimum 1 tag

***Manage Workflows***

![Screenshot 2023-03-29 at 2 43 16 PM](https://user-images.githubusercontent.com/6416247/228637041-e45aaf27-2cf5-4dfa-9a0f-ecf1586d0ce5.png)

- [ ] Once created, add the generate task workflow to the manage workflows tab (similar to the current Task Workflow) but with the chip label set to "Generation"
- [ ] Rename "Task Workflow" chip to "Peer Review"
- [ ] Rename "Distribution Workflow" chip to "Distribution"
- [ ] Create the same workflow structure with source, destination, and requirements as the Peer Review Workflow
- [ ] Delete and Play buttons should work for Distribution as they do for Peer Review, as well

***Workspace***
We will be making some changes to the workspace, these changes will apply to both Peer Review and Generation tasks
![Screenshot 2023-03-29 at 3 10 33 PM](https://user-images.githubusercontent.com/6416247/228643169-2e99a6cb-20ab-489e-bde8-8eea845d6d93.png)

- [ ] For both peer review and generation, move the title to group and workflow name to the top of the page (e.g., Group 3: SEL Challenges Brainstorm)
- [ ] For both peer review and generation, move the prompt just below the group and workflow name (e.g., What are four challenges...)
- [ ] For both, move the requirements just below the prompt as an unordered list (e.g., Create 4 posts; Tag each post at least once)
- [ ] For only the generation workflow, add a plus button that opens the Add Post modal. Submitting the post (1) adds it to the swiper tool and (2) increments the progress bars. 
- [ ] Generation workflow posts follow the same flow as Peer Review, moving from Pending, to Active, to Completed
- [ ] For both peer review and generation, once all requirements are met, the status is automatically set "Complete" (the "Mark as Complete" button can be removed as this is no longer needed
- [ ] For both peer review and generation, add a toggle button for View Draft & View Submitted that swaps the list of posts in the swiper from those that have yet to be submitted and those already submitted. This toggle should be defaulted to show the Drafts.
![Screenshot 2023-03-29 at 3 37 40 PM](https://user-images.githubusercontent.com/6416247/228649020-a9f47bcf-6b07-4f58-b591-1ed6c294804f.png)

**Comment by JoelWiebe** [comment]
@LunarFang416 Hope all is well. I've made quite a number of updates above. Let me know if any items are too big and we can move those to separate issues.
