### ISSUE TITLE
Make Workspace, Learner Model, Personal Board, and TODO tool embeddable

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#465]
The following apply only to teacher UIs and should NOT be viewable by any students
1. Add the "file copy" icon to every community canvas (tooltip: "Copy embeddable URL") <- [UPDATED]

- [ ] Remove the copy embeddable URL button from the board configurations and 
<img width="638" alt="Screen Shot 2022-12-28 at 8 14 26 PM" src="https://user-images.githubusercontent.com/6416247/209891057-8b879d20-ba96-45b7-a8e0-e0b52da2cd02.png">

- [ ] Add a "file copy" icon next to the task description icon in the top left of every community board

<img width="299" alt="Screen Shot 2022-12-28 at 8 08 15 PM" src="https://user-images.githubusercontent.com/6416247/209890707-fc90c6e0-0bab-4bb6-a265-b1505d183c85.png">

2. Add a generic personal board embeddable URL copy icon to each personal board

- [ ] As for community boards, also add the "file copy" icon next to the task description of every personal board
- [ ] However, the embeddable URL should be generic (e.g., /project/[project ID]/my-personal-board)?embedded=true) such that a user's request would return their personal board for that project (/projejct/[project ID]/board/[board ID])
- [ ] Design a means of directing each user to their own personal board when they request the generic personal board URL (i.e., as described above /project/[project ID]/my-personal-board would direct each user to that user's own personal board for that project: /projejct/[project ID]/board/[board ID])
- [ ] If the "embedded" parameter equals "true", then remove the nav bar and all back or home buttons such that the user cannot navigate away from the current page (as already done with the community board embed links)

3. Add the embeddable URL icon to each workspace
<img width="411" alt="Screen Shot 2022-12-28 at 8 27 41 PM" src="https://user-images.githubusercontent.com/6416247/209891819-7e9d28a9-01f7-46a9-ae64-d6ac7ce53971.png">

- [ ] Add the file copy icon next to the workspace title in the top left of the nav bar (e.g., /project/04a0c298-92d5-44af-bc09-2b6dbb880692/workspace?embedded=true)
- [ ] If embedded is set to true, the workspace should be returned without the nav bar (as already done with the board embed links)
- [ ] If the "embedded" parameter equals "true", then remove the nav bar and all back or home buttons such that the user cannot navigate away from the current page (as already done with the board embed links)

4. Add the embeddable URL icon to the CK Monitor page
- [ ] Add the file copy icon next to the CK Monitor title in the top left of the nav bar (e.g., /project/04a0c298-92d5-44af-bc09-2b6dbb880692/monitor?embedded=true)
- [ ] If embedded is set to true, the learner model should be returned without the nav bar (as already done with the board embed links)
- [ ] NOTE: Keep in mind that currently only the teacher uses the CK Monitor but in the future when students access this URL they should be presented with only the contents of their own learner model -- and not be able to see the task completion or user models of other students (this will be a separate issue)
- [ ] If the "embedded" parameter equals "true", then remove the nav bar and all back or home buttons such that the user cannot navigate away from the current page (as already done with the board embed links)

5. Make a TODO tool page with its own URL and embeddable URL

- [ ] Transition the TODO tool from a modal pop-up to its own page 
- [ ] Add the file copy icon next to the TODO title in the top left of the nav bar (e.g., /project/04a0c298-92d5-44af-bc09-2b6dbb880692/todo?embedded=true)
- [ ] If embedded is set to true, the workspace should be returned without the nav bar (as already done with the board embed links)

**Comment by JoelWiebe** [comment]
@LunarFang416 Would you be able to help me out by working on this in early January? If we get this built, we can test out activities near the start of this upcoming term that embed these in the SCORE system.

**Comment by LunarFang416** [comment]
@JoelWiebe In the case that a teacher copies the embed code for a students personal board it would just return the teachers personal board. 
Is that how we intend that to work?

**Comment by JoelWiebe** [comment]
@LunarFang416 Great question. I should have been clearer in the description. 

I was proposing the following:

- Clicking the copy button on any personal board (whether the personal board of student A, student B, or teacher A) would all copy the same url in the format /project/[project ID]/my-personal-board?embedded=true), however,
- When the teacher A opens that URL they are directed to teacher A's person board (their own)
- When student A opens that URL they are directed to student A's person board (their own)
- When student B opens that URL they are directed to student B's personal board (their own)

We could achieve this by routing the generic URL (e.g., /project/[project ID]/my-personal-board?embedded=true) to the user's own personal board URL (e.g., /project/[project ID]/board/[board ID]?embedded=true). What do you think about this? Do you see any issues with this?

**Comment by JoelWiebe** [comment]
@LunarFang416 I also added this directive for all embeddable components in the description above, just to be explicit: 

If the "embedded" parameter equals "true", then remove the nav bar and all back or home buttons such that the user cannot navigate away from the current page (as already done with the community board embed links)

Let me know if you have any questions or see any red flags. We can also meet to discuss!

**Comment by LunarFang416** [comment]
@JoelWiebe In the current board embed, we aren't able to navigate away from the page (by the back button or home button), but can still access the ck-workspace and ck-monitor modals.

I can configure it so that users can go to those pages, but when the press the back button from there, it will return to the embedded board page. How does that sound for you.

For the standalone embeds of the ck-monitor and ck-workspace, you wont be able navigate anywhere else.

**Comment by JoelWiebe** [comment]
@LunarFang416 Good catch, that's actually a bug. The workspace and ck-monitor must have been designed after the embed feature was designed.

All top (nav) bar icons and the nav bar itself should be removed. Only the canvas should be visible.

Thanks for your work on this!
