### ISSUE TITLE
Add Spinner and Pagination to List View

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#491]
### Description
The CK Bucket already has both a progress spinner and pagination. We will now add these to the List View. We will also now add Previous and Next buttons to the pagination tool. 

**Tasks**
1. Add the progress spinner to the List View

 - To see the previous implementation of the spinner, click on the View Buckets icon in the top nav bar
 - To see the List View WITHOUT the spinner, click on the List Posts icon in the top nav bar

- [ ] Add the progress spinner to the List View

2. Add the pagination tool to the List view

 -[ ] Add the pagination tool to the List View modal as it is already implemented in the CK Bucket modal

3. Add Previous and Next buttons to the List View

- [ ] In the List View modal, add a **Previous** button at the bottom of the posts on the **left** side that (a) is enabled when a previous page exists, (b) is disabled when NO previous page exists, and (c) moves the paginator to the previous page when clicked
- [ ] In the List View modal, add a **Next** button at the bottom of the posts on the **right** side that (a) is enabled when a next page exists, (b) is disabled when NO next page exists, and (c) moves the paginator to the next page when clicked
- [ ] The Previous and Next buttons should be the same width

4. Add Previous and Next buttons to the CK Bucket modal

- [ ] Add a Previous button as implemented for the List View
- [ ] Add a Next button as implemented for the List View

**Comment by JoelWiebe** [comment]
Hey @aperritano! Would you be interested in working on this one?

**Comment by JoelWiebe** [comment]
@aperritano I updated the description for the feature above, this should be a pretty quick and simple one to get you started.

**Comment by aperritano** [comment]
Sounds good 😄

**Comment by JoelWiebe** [comment]
@aperritano Thanks for your work on this! @Ammar-T do these proposed changes in order to add pagination to the list view look good to you?

**Comment by JoelWiebe** [comment]
@Ammar-T Have you had a chance to take a glance at this?

**Comment by JoelWiebe** [comment]
@Ammar-T Can you take a quick look at this? The pagination tool has been added to the list view but not yet fully functional as we are waiting to make a decision on the above. Your review would be much appreciated!

**Comment by JoelWiebe** [comment]
P.S. Here's the PR: https://github.com/encorelab/ck-board/pull/497

**Comment by Ammar-T** [comment]
Hey @aperritano, those changes look OK to me, go ahead with adding those in, thanks.
