### ISSUE TITLE
Prevent duplicate new posts and updates

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#509]
### Description
With a number of concurrent users, the Add Post modal occasionally remains open after the Add Post button is clicked allowing users to generate many duplicate posts 

**Details**
For a few students during an activity, the new post modal stayed stuck open until the student pressed it 25 times then it created all 25 posts on the board. This would imply that some kind of error had occurred during the creation of the post preventing the modal from closing (i.e., maybe an issue with web sockets or some other problem resulting from many concurrent users or DB updates). Do we think the switch to HTTP requests instead of web sockets would fix this or is there another fix that we should think about to ensure an opened modal can only be submitted one time?

**Task**

- [x] When the Add Post button is clicked, save the title and message to local storage then close the modal immediately
- [x] If the post was successfully saved, then do not display any message and delete the title and message from local storage
- [x] If an error occurred, open a snackbar with the message: "Unable to create post, please try again!"
- [x] If an error had occurred on the previous Add Post submission, then, when the Add Post modal is opened, populate the title and message fields with the saved values
- [x] If no error occurred on the previous Add Post submission, then, when the Add Post modal is opened, the title and message fields should be blank (as per usual)
