### ISSUE TITLE
Handle Latency Issues for UI Controls

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#513]
### Description
It was noticed that network latency can create various issues across CK Board, for instance, by allowing users to repeatedly press a button until the expected effect occurs 

**Details**
We began by addressing this issue for the Add Post button whereby repeatedly pressing that button can end up generating many posts (https://github.com/encorelab/ck-board/pull/511). We implemented a means of disabling the button after it is clicked once, then closing the modal after 5 seconds and producing a snackbar error message. We can apply this standard across other contexts, most importantly any settings modal. 

**Tasks**

- [ ] Add disable-spinner-error pattern to Update Configuration button in **Board configuration modal** (from canvas and project dashboard views) with error message: "Unable to update board configurations. Please refresh and try again!

![Screenshot 2023-03-23 at 6 08 01 PM](https://user-images.githubusercontent.com/6416247/227375711-d04a80dd-7df3-4e1d-80bf-9272346f05c6.png)

- [ ] Add disable-spinner-error pattern to Update Configuration button in **Project Configuration** modal (from canvas and project dashboard views) with error message: "Unable to update board configurations. Please refresh and try again!

- [ ] Add disable-spinner-error pattern to Add Tag button in the **Add Post modal** with error message "Unable to add tag. Please refresh and try again!"

![Screenshot 2023-03-23 at 5 37 36 PM](https://user-images.githubusercontent.com/6416247/227369670-124b412d-324b-4ee9-9265-b106917cfa91.png)

- [ ] Add disable-spinner-error pattern to Add Tag button in the **view post modal** with error message "Unable to add tag. Please refresh and try again!"

- [ ] Add disable-spinner-error pattern to Update button in the **edit post modal** with error message "Unable to update post. Please refresh and try again!"

- [ ] Add **disable-spinner** pattern to all Cancel/Close buttons in those modals WITHOUT any error message

**Comment by JoelWiebe** [comment]
**Details**
For some reason most error messages were not displaying for me. Perhaps missing some latest changes. I have left my suggestions below. In each case I have throttling turned off while navigating to the appropriate view, then set my browser network settings to offline.

**Tasks**
- [ ] When updating the Board Configurations while offline, I am getting the following error (shown below). Could we simplify this message for the user (to also be consistent with Ammar's previous Add Post error message): "Unable to update board configurations. Please refresh and try again!"

<img width="799" alt="Screenshot 2023-07-05 at 11 13 44 AM" src="https://github.com/encorelab/ck-board/assets/6416247/3cfef119-eaf3-476d-a968-7b840c3b8421">

- [ ] For the board configurations, if I turn the browser offline either before I open the project modal or after I open the project modal then press the Update button, the button either spins and closes (without an error message) or spins indefinitely (without an error message). Can we ensure the following message is being displayed: "Unable to update board configurations. Please refresh and try again!"

- [ ] On the Add Post modal, I am able to add a tag to the post and there is no error. Can we (1) have the tag fail to be visually added to the post (as with the View Post modal) and (2) ensure the following error message is displayed when the user clicks to add a tag: "Unable to add tag. Please refresh and try again!"

- [ ] When the tag fails to be added in the View Post modal, can we display the error message: "Unable to add tag. Please refresh and try again!"

- [ ] When editing the title or the message of a post, when the Update button is pressed after editing the title or message, can we display an error message: "Unable to update post. Please refresh and try again!"

@DCH25 Perhaps we've been using different means of simulating latency or network issues. Please let me know if you have any questions or would like to discuss anything!
