### ISSUE TITLE
Performance Issues with Concurrent Users

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#520]
### Description
We have been noticing some strange performance/functionality issues (e.g., post creation errors, moving posts getting stuck, trace logs not logging student actions) when a class of students are using CK Board (e.g., 16 - 30 students). 

**Details**
These issues have started to cause issues for my data collection in classrooms. For some reason, everything seems to work okay with one user or even a couple, but when we get a class of students some strange things start happening resulting in errors while performing post actions (e.g., attempts to create posts return errors, moving posts stay stuck greyed out in the process of being moved, other changes to posts such as comments or tags may not take effect, etc.) resulting in these actions sometimes not performing gracefully and not being logged in our trace logs. 

**Tasks**

- [ ] Resolve issues with creation of posts occasionally throwing an error when Add Post button is pressed (with concurrent users)

- [ ] Resolve issue with modifying a post (e.g., comment, tag, upvote) occasionally not taking effect

- [ ] Ensure trace logs are saving all student actions, (e.g., create post, comment, tag, upvote) when trace logs are enabled (from the Settings found in the canvas menu)

![Screen Shot 2023-04-04 at 11 02 39 AM](https://user-images.githubusercontent.com/6416247/229834975-063ba2a9-6339-4a59-9fb5-18c0f62e60cb.png)

NOTE: One solution may involve ensuring we are using HTTP requests for all of these actions and ensuring we are not using web sockets for these changes (we made this change for our workspace already -> https://github.com/encorelab/ck-board/pull/494)
