### ISSUE TITLE
Set Max Board Size

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#554]
### Description
Posts can get easily lost in an infinite space. To remedy this we would like to investigate limiters on the size of a canvas.

**Details**
We can likely assume that the canvas can always be a square so we only need to set one value. We will need to investigate whether and if so how to limit the space of the canvas. This will have implications for the zoom and panning to restrict the user to a finite space.

**Tasks**

- [ ] Find and set a minimum value for the size of the canvas, for simplicity we can call this value "1"
- [ ] Add a slider to the board configurations for the board size with one as the min reasonable value and perhaps "10" as the max size (we may allow increments by 0.5)
- [ ] The user should not be able to zoom beyond the limits of the canvas
- [ ] The user should not be able to pan beyond the limits of the canvas
