### ISSUE TITLE
Create learner model student view

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#558]
### Description
Create a version of the CK Monitor that is visible to students, allowing them to see their personal learner model data

**Tasks**

- [ ] Make the CK Monitor button in the menu visible to all students
- [ ] Make the CK Monitor page able to be displayed differently for teachers and students, making the following changes for students
- [ ] Remove the left pane (including the Pending/Active/Completed Tasks, View TODO button, and View Learner Model button) for students
- [ ] Remove the student selector in the top right corner for students
- [ ] Remove the Copy Embeddable URL button for students
- [ ] Modify the content of the page so that students can only see their personal learner model data (as shown below)
<img width="1358" alt="Screenshot 2023-07-19 at 11 39 41 AM" src="https://github.com/encorelab/ck-board/assets/6416247/7a4b8360-7ba0-4469-a45b-cbb5f820e1e1">

- [ ] Ensure that the teacher's Copy Embeddable URL button still works
- [ ] Ensure that when the students access the Embeddable URL for the CK Monitor, that they are routed to their personal data
