### ISSUE TITLE
Create Bucket View

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#560]
### Description
Create a bucket view, allowing users to toggle between the canvas view and the bucket view. The teacher may also disable either the bucket view or canvas view for students.

**Details**
The bucket view should have its own URL, distinct from the canvas view. The teacher will have the permissions to add or remove buckets from the bucket view. There will be a maximum of 4 buckets that can be displayed.

**Tasks**

- [x] By default the bucket view is available to students as a menu item and a button in the nav bar
- [x] By default the bucket view is blank, displaying a message indicating a "No buckets available"
- [x] The teacher will have a small button (always positioned on the right side of the right-most bucket) for adding new buckets to the view; this button disappears after four buckets have been added
- [x] Students will not see this button
<img width="213" alt="Screenshot 2023-07-19 at 12 16 31 PM" src="https://github.com/encorelab/ck-board/assets/6416247/d5927f96-3fb0-4e4d-abbf-1a776165e6f5">

- [x] Clicking the Add Bucket button may present a menu of buckets to choose from, ending with a Create New Bucket option
<img width="224" alt="Screenshot 2023-07-19 at 12 21 02 PM" src="https://github.com/encorelab/ck-board/assets/6416247/204063a9-b341-499c-b341-91689e7566e7">

- [x] Clicking the Create New Bucket option opens the Manage Buckets & Workflows pop-up to the tab for creating a new bucket
- [x] Each bucket may be presented similar to how they are presented as they do regularly <img width="418" alt="Screenshot 2023-07-19 at 12 27 13 PM" src="https://github.com/encorelab/ck-board/assets/6416247/882b60a1-ca80-457b-834c-7b458a8932ae">

- [x] The X in the right hand corner of each bucket is visible to only teachers to remove the bucket from the bucket view (the X is hidden in the bucket viewer from students)
- [x] (Optional) as a stretch goal, let's consider allowing students and teachers to drag posts between different buckets using the bucket viewer

**Comment by JoelWiebe** [comment]
@vkorir would you be interested in working on this, to break up the other work you've been doing?

**Comment by vkorir** [comment]
Yes, sure I'll take up this.
--
Regards,
Victor
