### ISSUE TITLE
Update Board/Project Configuration Labels

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#568]
### Description
Move an item in Project Configuration pop-up (only the one creating new boards) and rename move and rename some items in the Board configurations pop-up (the ones for both creating and modifying boards). 

**Tasks**
(Creation) Project Configuration Modal

- [x] In the Project Configuration pop-up (for creating new projects), move the checkbox for "Create Personal Boards for Project Members" from the Personal Boards tab to underneath "Project Name" in the Project tab (see image below)
- [x] Remove the "Personal Boards" tab (and consider removing the tab label for Project -- since there is now only one tab) for creating new boards
- [x] Project configurations for editing a project may remain unchanged
![Screenshot 2023-10-23 at 12 17 55 PM](https://github.com/encorelab/ck-board/assets/6416247/ec6c8eff-c9e9-4c26-a6c8-40726676e76b)

(Creation and Modification) Board Configurations Modals
- [x] Rename “Allow tracing of board activity” to “Enable logging of all user activities”
- [x] Rename “Brainstorming” to “Idea generation”
- [x] Rename “Back to project” to “Back to projects”
- [x] Rename “Background” to “Board” and move the Initial Zoom component to below the "Board" heading
