### ISSUE TITLE
Add AI-powered classification workflow

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#570]
### Description
Create a new workflow type used to classify posts from a source bucket into a specified number of destination buckets.

**Details**
Create an additional workflow type that will take as input a workflow name, a source bucket (containing the posts to be classified), and the number of categories into which the posts can be organized. Classification will use Google's PaLM API for classification. This workflow will automatically create a new bucket for each category, move the posts into the corresponding buckets (identified by the PaLM model), and modify the bucket view to contain only the newly created buckets with assigned posts.

**Tasks**
<img width="1052" alt="Screenshot 2023-11-22 at 11 56 05 AM" src="https://github.com/encorelab/ck-board/assets/6416247/cdb2fd5c-719d-4c68-a418-266ac44b9198">

- [ ] Add a new workflow type called "AI Classification" to the Create Workflows tab in the Manage Workflows tool
- [ ] Add a Source field used to select from any bucket or the canvas
- [ ] Add a # Categories (or Num Categories) field that can be a slider, selector, etc. with values from 2 to 10; as a default, let's set this to 4
- [ ] To begin, let's use the Language Tasks for PaLM API firebase extension for classification; to authenticate, let's use a private key generated from firebase
- [ ] Create prompts to generate the specified number of classification categories and classify each of the posts into one of those specified categories
- [ ] Verify that the number of classification categories provided by the LLM matches the requested number of categories, then use the given classification names to create a new bucket for each of the classification categories
- [ ] Move the posts to the destination buckets according to assigned values; verify that each assigned value matches one of the bucket names created 
- [ ] Run this workflow from the Manage Workflows tab and display any errors to the teacher as a snackbar message (e.g., # Categories Mismatch: x number of categories created, y number requested; Post Assignment Mismatch: x number of post assignments to categories outside of category list) 
- [ ] Update the bucket view to display the buckets that were just created

<img width="1056" alt="Screenshot 2023-11-22 at 12 24 57 PM" src="https://github.com/encorelab/ck-board/assets/6416247/370ce75a-fbc4-46e3-b7a4-12cb58f2b96c">

**Comment by JoelWiebe** [comment]
@LunarFang416 Here are two resources related to classification prompts:

- An OpenAI example that suggests using JSON to structure the text snippets
- A PaLM API example that suggests adjusting temperature and top-K to be more deterministic (in Firebase extension configurations in our case I believe)

The above assumes we already have categories. To generate our own categories, we could use a prompt such as the following:

_Analyze the provided text snippets and identify the four most prominent categories that effectively summarize the overall content. Each category should represent a distinct theme or topic that encompasses the key ideas presented in the snippets. Ensure that the categories are concise, informative, and accurately reflect the essence of the text snippets.

Text snippets:
[Insert your text snippets here]_

We could try displaying the text snippets as independent paragraphs or in JSON format. Also, in both cases, we could try classification with only the body text or with the title text followed by the body text to see if this makes much of a difference. Let me know if you want me to play around with this too! We can also run this in a classroom to get some real data as we design these prompts.

**Comment by JoelWiebe** [comment]
Using Teacher (AI Assistant) Agent instead
