### ISSUE TITLE
Add "Individual Work" Option to Generative Task Workflow

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#572]
### Description
Add an additional option for Individual Work to the Generation Task Workflow that involves selecting only a single group whereby all members of that group must each complete the assigned task.
![Screenshot 2023-11-30 at 3 44 58 PM](https://github.com/encorelab/ck-board/assets/6416247/98188167-ea57-47e5-a824-4ae83274f7b8)

**Details**
This will add an "Individual Work" option to the Generation Task workflow (under the Create Workflow tab). When selected, the "Assigned Groups" (multi-selection) will be replaced with an "Assigned Members" (single-selection). The current Generation Task workflow involves sending the same generation task to all members of a group (and is marked as complete when any member of the group completes the work), but with Individual Work each member receives their own copy of the task and is only completed when that individual completes the work. 

**Tasks**

- [x] Add a new radio button group with options for "Group Work (assigned to each group)" and "Individual Work (assigned to each member", under the "Destination" selector.
- [x] When Individual Work is selected, replace the "Assigned Groups" multi-group selector with an "Assigned Members" (single-group selector; as a required field)
- [x] When Group Work is selected, the "Assigned Groups" multi-group selector should be displayed and the Workflow and Workspace should behave as before
- [x] Running the Individual Work, Generation Task workflow should assign a copy of the task to each individual member of the selected single group
- [x] Let's remove the Pending Tasks section in the Workspace sidebar (as shown below) and have all new tasks added directly to Active Tasks (we can either continue to use the "Begin Task" button for starting a new task or use only the "Show/Hide Task" buttons for Active Tasks once the Pending Tasks and Active Tasks are merged)
![Screenshot 2023-11-30 at 4 57 42 PM](https://github.com/encorelab/ck-board/assets/6416247/2fdec3de-798e-4156-aa2f-41922e24a3fe)

- [x] Each individual is responsible for completing their own Individual Work tasks in the Workspace, this is denoted by replacing the "Group [#]: [name]" field in the Workspace sidebar with "Individual: [workflow name]"
![Screenshot 2023-11-30 at 4 19 22 PM](https://github.com/encorelab/ck-board/assets/6416247/f50d0414-f91e-4ebe-837a-341239db9395)

- [ ] Group tasks are currently denoted in the sidebar with "Group [#]: [student prompt]", let's swap that with "Group [#]: [workflow name]

-  Let's clean up the UI with a bunch of small changes, as seen below 
![Screenshot 2023-11-30 at 4 42 04 PM](https://github.com/encorelab/ck-board/assets/6416247/88ab43d7-d7ce-432f-9819-ed9548aec787)

- [x] Remove the group number from the workflow title (at the top of the page) and set the font-weight to bold and the margin to 15px (all directions)
- [x] For the prompt, switch it to a paragraph element, set the font-size to 18px, and set the margin to 15px (all directions)
- [x] Move the task (e.g., Create 1 Post) to underneath progress bars with the text "Task:" above it
- [ ] "Group Members" should be replaced with "Group [#]:"
- [x] The "Task:" and "Group [#]:" text should switched to paragraph elements
- [x] For Individual Work tasks, the "Group [#]:" label and members list can be removed (as seen below)
![Screenshot 2023-11-30 at 4 55 15 PM](https://github.com/encorelab/ck-board/assets/6416247/d260b25d-4bb5-4488-812b-22796325a6dc)

**Comment by JoelWiebe** [comment]
@DCH25 @LunarFang416 Would either of you be interested in this one?

**Comment by JoelWiebe** [comment]
@markiianbabiak Are you interested in this one? Somehow it completely got missed but will be very important for using the workspace with large class sizes.

**Comment by markiianbabiak** [comment]
"Group tasks are currently denoted in the sidebar with "Group [#]: [student prompt]", let's swap that with "Group [#]: [workflow name]" - Wouldn't this be a repetition of the workflow name tho? @JoelWiebe

**Comment by markiianbabiak** [comment]
"Group Members" should be replaced with "Group [#]:" - the groups don't have numbers, and the group name isn't necessarily in a format "Group [#]:" - are you sure you want to proceed with this? @JoelWiebe

**Comment by JoelWiebe** [comment]
@markiianbabiak Good push back on these. I created this issue over a year ago and not sure what I was thinking at the time.

At a glance, it would make sense to me to do the following:

- [ ] In the task list side pane, let's leave [Group name]: [Student prompt] as is for groups if that is what we have, but for individual tasks we can switch this to Individual: [Student prompt]
- [ ] In the progress bar, for group tasks, let's replace "Group Members:" with "Group: " [Group name]
- [ ] In the progress bar, for individual tasks, let's replace the group membership with "Individual Task"

Does that sound more reasonable? Am I understanding the current state correctly?

**Comment by markiianbabiak** [comment]
@JoelWiebe Let's discuss this in our meeting today

**Comment by markiianbabiak** [comment]
@JoelWiebe We also have to rethink the ck-monitor view. Right now, when you assign a task to a couple of people/groups, as long as all of them haven't completed the task it shows up correctly, as part of one task. But the moment one person completes the task, it splits it up into 2 tasks, with one only showing the people/groups who completed the task and the other showing only the people/groups, who still have the task going. So my thinking is, instead of grouping it by tasks, we can group it by workflows so that if at least one of the people/groups hasn't completed the task, it will show up as active and have them all together, instead of having them split up into completed and active parts.
