### ISSUE TITLE
FEATURE: Offset posts moved automatically to the canvas

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#578]
### Feature
**Overview**
Posts added to the canvas by a generation workflow are stacked exactly on top of one another, making it look like there is only one post. We need to make it apparent that multiple posts exist.

**Details**
One means of making all posts visible is to vertically and horizontally offset them, as shown below. If possible, the first post for a particular generative workflow for a particular group can be added in a random location near the centre of the canvas, then each consecutive post can be slightly vertically and horizontally offset from the first (as shown in the image below). 

**Setup**
 - Create two or more generative task workflows for two or more groups

**Tasks**
- [ ] For each generative workflow task, add the first post created by a particular group for a particular generative task workflow to a random location near the centre of the canvas
- [ ] Set consecutive posts for a particular group for a particular generative task workflow slightly offset vertically and horizontally from the first (see image below)
- [ ] If one group completes two generative tasks, the posts should land in separate offset stacks
- [ ] If another group creates two generative tasks, the posts should land in different offset stacks from the first group (see image below)
- [ ] Similarly if in the Bucket view and clicking to download posts, the first post should be added randomly near the centre of the canvas and consecutive posts clicked on should be vertically and horizontally offset in the same stack

**Screenshots**
![Screenshot 2024-04-13 at 4 13 47 PM](https://github.com/encorelab/ck-board/assets/6416247/bcdd5cdf-0608-48cd-bdb3-3e7c6fba3dee)
