### ISSUE TITLE
FEATURE: Create a mobile friendly workspace view

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#589]
### Feature
**Overview**
Create a mobile-responsive version of the Workspace view

**Details**
The workspace may commonly be used from cell phones or tablets whereas the canvas will continue to be used primarily on computers and large classroom displays

**Tasks**
- [ ] Create a responsive nav bar (with view icons)
- [ ] Make side panel collapsible only on mobile (closes when option selected from mobile)
- [ ] Add expand/collapse arrow
- [ ] Test to ensure flip through posts works on mobile
- [ ] Update post pop-up responsiveness for mobile

**Comment by JoelWiebe** [comment]
@markiianbabiak would this interest you?

**Comment by JoelWiebe** [comment]
This is the current view of the CK Workspace.
![Screenshot 2024-06-25 at 12 09 37 PM](https://github.com/encorelab/ck-board/assets/6416247/22b30711-e6b9-4b96-8b64-2366df9979d5)

To Setup:

- In a board, go to Manage groups in top right menu to create at least one group and assign yourself to that group
- Create at least one post on the canvas
- In that same top right menu, go to Manage Buckets and Workflows and ensure at least one bucket is created 
- Create either a generation or peer review workflow, the in Manage Workflows, click the play button
- Then go to the CK Workspace to see your task
