### ISSUE TITLE
FEATURE: Create SCORE Runs

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#593]
### Feature
**Overview**
Create the notion of a SCORE Run, that is an runtime environment that is linked to a particular CK Board instance.

**Details**
Create a "My SCORE Runs" section in the projects dashboard. A SCORE Run is another type of project, it contains the same boards, buckets, workflows, and groups elements from a standalone CK Board project. SCORE Runs also have access codes, similar to standalone projects. SCORE Runs, however, have the ability to be scripted into sequential phases of activities. 

**Tasks**
- [x] In the projects dashboard menu, add a Create SCORE Run option and rename Create Project to "Create Standalone CK Project"
<img width="483" alt="Screenshot 2024-07-04 at 12 14 31 AM" src="https://github.com/encorelab/ck-board/assets/6416247/4990c453-7fb4-4a6d-8b52-829c70d62c74">

- [x] Create a "My SCORE Runs" section on the projects dashboard and display created SCORE Runs here
<img width="735" alt="Screenshot 2024-07-04 at 12 39 13 AM" src="https://github.com/encorelab/ck-board/assets/6416247/e909bd58-68f2-4ec3-94d0-91051ae11a2f">

- [x] Also rename the CK Boards section to "My Standalone CK Projects"
- [ ] Add an info icon next to My SCORE Runs and My Standalone CK Projects with a tooltip describing their differences
- [ ] Within a standalone project and a SCORE project, change the contained items on the dashboard from boards to projects (e.g., "Shared CK Projects", "Student CK Projects", "Teacher CK Projects")
- [ ] For SCORE Runs, each contained CK Project should hide the toggle visibility icon

- [ ] SCORE Runs are essentially the same as a project, but the tabs displayed for each student are dependent on the "Phase" (or Script) being performed; therefore, let's add a distinguishing backend tag to distinguish between a "CK Project" and "SCORE Run".
- [ ] When creating a CK Project, let's rename the pop-up to "CK Project Configuration", remove the Personal tab, and add the checkbox from the personal tab as the first checkbox in the main project tab
<img width="691" alt="Screenshot 2024-07-04 at 12 51 26 AM" src="https://github.com/encorelab/ck-board/assets/6416247/3275d98e-a320-41ab-a52e-98d492d06cfb">

- [ ] When a SCORE Run is created, rename the pop-up to SCORE Run Configurations and adjust other tabs and labels as displayed below

- [x] Add Teacher Agent button to SCORE Authoring
- [x] Hide Script SCORE button from students
- [x] Add URL to join code
- [x] Fix bucket view display in SCORE Authoring
