### ISSUE TITLE
FEATURE: Add picture attachments to posts

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#602]
### Feature
**Overview**
Add ability to upload and view images in all posts

**Details**
Migrate image storage from deprecated Firebase implementation to MongoDB and add the ability to attach an image to each post

**Tasks**
- [ ] Implement MongoDB database implementation for image storage
- [ ] Test implementation using the existing background image for canvases feature
- [ ] Add button to each post in edit view to upload an image
- [ ] Add a button to each post in the edit view to delete the image (include a confirmation dialogue)
- [ ] Perform angular compression of the image and store in MongoDB
- [ ] Display image at a default max height and max width in the view post modal
- [ ] Display an icon on the post card on the canvas, bucket view, workspace, etc. if the post contains an image
