### ISSUE TITLE
FEATURE: Add AI Assistant

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#604]
### Feature
**Overview**
Create an AI assistant that can provide insights into post content within a project

**Details**
Provide read only access to the database data, bucket and canvas assignments of posts, and post data and metadata to answer questions.

**Tasks**
- [x] Add a Vertex AI service in the backend 
- [x] Allow the service access to the entire current project's post data and metadata
- [x] Create a query template that allows custom requests to be sent the the LLM client service
- [x] Create a frontend UI that allows the teacher to send queries and receive responses from the LLM service

**Comment by JoelWiebe** [comment]
<img width="696" alt="Screenshot 2024-10-08 at 10 35 38 PM" src="https://github.com/user-attachments/assets/33dc6536-b707-4b86-99b6-2a197fa1008f">

We have an AI Assistant!
