### ISSUE TITLE
FEATURE: Add AI Assistant Chat Log Downloads

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#625]
### Feature
**Overview**
Add AI Assistant chat logs to database and create a download button

**Details**
For the AI Assistant, log all chat messages to the data base and create a download button where each teacher can download their own chat history.

**Tasks**
- [x] Create a database schema for saving chat logs, including the teacher's user ID, role (whether user or assistant), the timestamp, the board ID, and the content
- [x] Each time a user creates a prompt, save the prompt with the 'user' role
- [x] Each time the AI assistant creates a response, save the response with the 'assistant' role
- [x] Create a Download Chat History button in the AI assistant tab
- [x] When the download button is pressed, retrieve the entire chat history and save as a CSV file that is downloaded by the client
