### ISSUE TITLE
FEATURE: Add Oct 29, 2024 Research Study Request Updates

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#632]
### Feature
**Overview**
Perform minor updates for classroom runs related to button access, AI assistant data, and websockets

**Tasks**
- [x] Remove student access to manual bucket assignments for posts
- [x] Add student info to AI Assistant context
- [x] Improve error handling for ECONNRESET
- [x] Remove Go to SCORE menu option
